import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {options,number,CDP,writeJSON,readJSON,readText,containedPath,assertDistinctPaths,acquireLock,findExecutable} from '../web-debug/scripts/common.mjs';
import {safeURL,summarizeReport,compareReports} from '../web-debug/scripts/diagnostics.mjs';
import {validatePlan} from '../web-debug/scripts/plan.mjs';
const exec=promisify(execFile),kit=fileURLToPath(new URL('..',import.meta.url));
async function fixture(){const base=path.resolve('work/adversarial-tests');await fs.mkdir(base,{recursive:true});return fs.mkdtemp(path.join(base,'case-'));}
async function cli(script,argv,expected=0){try{const r=await exec(process.execPath,[path.join(kit,script),...argv],{windowsHide:true,timeout:12000,maxBuffer:2000000});assert.equal(expected,0);return r.stdout;}catch(e){if(expected&&e.code===expected)return e.stderr;throw e;}}
test('strict CLI rejects unknown switches and boolean values',()=>{assert.throws(()=>options(['--securty'],[],['security']),/Unknown/);assert.throws(()=>options(['--security','false'],[],['security']),/flag/);assert.throws(()=>options(['--out'],['out']),/Missing/);assert.throws(()=>options(['--_','wrong']),/Duplicate|Unknown/);});
test('numeric validation rejects booleans, null and whitespace',()=>{for(const v of [true,false,null,'',' ','Infinity'])assert.throws(()=>number(v,10,0,100));assert.equal(number('1.5',10,0,100),1.5);});
test('all main CLIs reject an unknown option even with --help',async()=>{for(const name of ['chrome','project','analyze','copy','edge','github','refresh','report'])assert.match(await cli(`web-debug/scripts/${name}.mjs`,['--help','--unrecognized'],1),/Unknown option/);});
test('copy output cannot overwrite its input, including hardlink aliases',async()=>{const dir=await fixture(),input=path.join(dir,'input.txt'),alias=path.join(dir,'alias.txt');await fs.writeFile(input,'Original text must be preserved.');await fs.link(input,alias);assert.match(await cli('web-debug/scripts/copy.mjs',['--file',input,'--out',alias],1),/distinct/);assert.equal(await fs.readFile(input,'utf8'),'Original text must be preserved.');});
test('analysis output cannot overwrite a source report or another output',async()=>{const dir=await fixture(),report=path.join(dir,'report.json');await writeJSON(report,{ok:true,steps:[],events:[]});assert.match(await cli('web-debug/scripts/analyze.mjs',['--report',report,'--out',report],1),/distinct/);await assert.rejects(assertDistinctPaths([],[report,report]),/distinct/);});
test('atomic output refuses a symbolic-link target and preserves the outside file',async()=>{const dir=await fixture(),outside=path.join(dir,'sentinel.txt'),link=path.join(dir,'out.json');await fs.writeFile(outside,'preserve');await fs.symlink(outside,link,'file');await assert.rejects(writeJSON(link,{changed:true}),/symlink/);assert.equal(await fs.readFile(outside,'utf8'),'preserve');});
test('cache paths reject an escaping junction while allowing ordinary nested paths',async()=>{const dir=await fixture(),cache=path.join(dir,'cache'),outside=path.join(dir,'outside');await fs.mkdir(cache);await fs.mkdir(outside);await fs.symlink(outside,path.join(cache,'snapshots'),process.platform==='win32'?'junction':'dir');await assert.rejects(containedPath(cache,'snapshots/example.txt'),/outside/);assert.equal(await containedPath(cache,'ordinary/file.txt'),path.join(cache,'ordinary/file.txt'));});
test('bounded file input refuses oversized files',async()=>{const dir=await fixture(),file=path.join(dir,'large');await fs.writeFile(file,'x'.repeat(100));await assert.rejects(readText(file,10),/larger|exceeds/);});
test('Windows UTF-16 JSON preserves Unicode and rejects incomplete code units',async()=>{const dir=await fixture(),file=path.join(dir,'utf16.json');await fs.writeFile(file,Buffer.concat([Buffer.from([255,254]),Buffer.from(JSON.stringify({name:'ภาษาไทย'}),'utf16le')]));assert.equal((await readJSON(file)).name,'ภาษาไทย');await fs.appendFile(file,Buffer.from([1]));await assert.rejects(readJSON(file),/UTF-16/);});
test('operation lock rejects a second owner and permits reuse after release',async()=>{const dir=await fixture(),file=path.join(dir,'operation.lock');const release=await acquireLock(file);await assert.rejects(acquireLock(file),/locked/);assert.equal(JSON.parse(await fs.readFile(file,'utf8')).pid,process.pid);await release();await (await acquireLock(file))();});
test('malformed CDP events do not crash clients and mark protocol uncertainty',()=>{const socket=new EventTarget();socket.send=()=>{};socket.close=()=>{};const cdp=new CDP(socket);cdp.on(()=>{throw new Error('bad event shape');});for(const data of ['null','[]','42','{','{"method":"Runtime.consoleAPICalled","params":{}}'])socket.dispatchEvent(new MessageEvent('message',{data}));assert.equal(cdp.protocolErrors,5);cdp.close();});
test('contradictory success is not reported as a passing complete capture',()=>{const r={ok:true,steps:[{type:'assert',ok:false,error:'failure'}],events:[]};const s=summarizeReport(r);assert.equal(s.scenarioPassed,false);assert.equal(s.captureComplete,false);assert(s.findings.some(f=>f.code==='inconsistent-report'));assert.equal(compareReports(r,r).comparable,false);});
test('malformed or empty reports cannot claim successful capture',()=>{assert.throws(()=>summarizeReport({ok:true,steps:[null],events:[]}),/Malformed/);assert.throws(()=>summarizeReport({ok:true,steps:[],events:[]}),/Malformed/);});
test('inline data and JavaScript URL payloads are omitted',()=>{assert(!safeURL('data:text/plain,'+'private'.repeat(10000)).includes('private'));assert(safeURL('data:text/plain,abc').length<100);assert(!safeURL('javascript:alert("secret")').includes('secret'));});
test('plan validation rejects a bad final action before any execution',()=>{assert.throws(()=>validatePlan({actions:[{type:'eval',expression:'window.changed=true'},{type:'typo'}]},{allowScript:true}),/Unknown action/);assert.throws(()=>validatePlan({actions:[{type:'fill',selector:'#x',text:'a',file:'inputs/b'}]}),/exactly one/);assert.throws(()=>validatePlan({actions:[{type:'viewport',mobile:'false'}]}),/boolean/);assert.throws(()=>validatePlan({actions:[{type:'traceStart'}]}),/traceStop/);});
test('deterministic malformed-plan mutation corpus is rejected without side effects',()=>{const values=[null,true,false,0,NaN,'',[],{},'constructor','__proto__'];let cases=0;for(const a of values)for(const b of values){assert.throws(()=>validatePlan({actions:[{type:a,[String(b)]:b}]}));cases++;}assert.equal(cases,100);});
test('knowledge status verifies evidence and treats malformed dates as overdue',async()=>{const dir=await fixture(),sha=createHash('sha256').update('absent').digest('hex');await writeJSON(path.join(dir,'ledger.json'),{schema:2,sources:{baseline:{sha256:sha,reviewedSha256:sha,snapshot:'snapshots/missing.txt',reviewedAt:'invalid-date'}}});const status=JSON.parse(await cli('web-debug/scripts/refresh.mjs',['status','--out',dir])).find(x=>x.id==='baseline');assert.equal(status.reviewRequired,true);assert.equal(status.reviewOverdue,true);assert.match(status.snapshotProblem,/missing/i);});
test('knowledge review refuses a snapshot junction escape without writing history',async()=>{const dir=await fixture(),cache=path.join(dir,'cache'),outside=path.join(dir,'outside');await fs.mkdir(cache);await fs.mkdir(outside);const content='Harmless fixture evidence in another directory.',sha=createHash('sha256').update(content).digest('hex');await fs.writeFile(path.join(outside,'source.txt'),content);await fs.symlink(outside,path.join(cache,'snapshots'),process.platform==='win32'?'junction':'dir');await writeJSON(path.join(cache,'ledger.json'),{schema:2,sources:{baseline:{sha256:sha,snapshot:'snapshots/source.txt'}}});const note=path.join(dir,'note.txt');await fs.writeFile(note,'A sufficiently detailed but intentionally adversarial review fixture note.');assert.match(await cli('web-debug/scripts/refresh.mjs',['review','--out',cache,'--id','baseline','--sha256',sha,'--note-file',note],1),/outside/);await assert.rejects(fs.access(path.join(cache,'reviews.jsonl')));});
test('unsupported ledger schemas cannot be silently migrated',async()=>{const dir=await fixture();await writeJSON(path.join(dir,'ledger.json'),{schema:999,sources:{}});assert.match(await cli('web-debug/scripts/refresh.mjs',['migrate','--out',dir],1),/Unsupported/);assert.equal(JSON.parse(await fs.readFile(path.join(dir,'ledger.json'),'utf8')).schema,999);});
test('executable lookup ignores relative PATH entries',async()=>{const previous=process.env.PATH;try{process.env.PATH='.';await assert.rejects(findExecutable('git'),/absolute PATH/);}finally{process.env.PATH=previous;}});
test('compact entry point retains complete output and supports --full',async()=>{const dir=await fixture(),input=path.join(dir,'copy.txt'),output=path.join(dir,'copy.json');await fs.writeFile(input,'ตรวจสอบรายการก่อนยืนยัน');const compact=JSON.parse(await cli('web-debug/scripts/debug.mjs',['copy','--file',input,'--language','th','--out',output]));assert.equal(compact.output,output);assert(JSON.parse(await fs.readFile(output,'utf8')).metrics.words>0);const full=JSON.parse(await cli('web-debug/scripts/debug.mjs',['copy','--file',input,'--language','th','--out',output,'--full']));assert(full.metrics.words>0);});
