import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {fileURLToPath} from 'node:url';
import {args,required,writeJSON,CDP,fetchJSON,delay} from '../web-debug/scripts/common.mjs';
const exec=promisify(execFile),o=args(process.argv.slice(2)),work=path.resolve(required(o,'work'));await fs.mkdir(work,{recursive:true});
const cli=fileURLToPath(new URL('../web-debug/scripts/chrome.mjs',import.meta.url)),gateway=fileURLToPath(new URL('../web-debug/scripts/debug.mjs',import.meta.url)),state=path.join(work,'state');
const checks=[],performanceEvidence={};const pass=name=>{checks.push(name);console.log('PASS '+name);};
const server=http.createServer((q,r)=>{r.writeHead(200,{'Content-Type':'text/html'});r.end('<input id="text" value="old"><input id="other" value="untouched"><input id="check" type="checkbox"><div style="opacity:0"><button id="hidden" onclick="window.hiddenClicked=true">Hidden</button></div>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
async function command(command,extra=[],expected=0){const trusted=command==='launch'?['--allow-tcp-debugging']:command==='run'?['--allow-script','--overwrite']:[];try{const r=await exec(process.execPath,[cli,command,'--state-dir',state,...trusted,...extra],{windowsHide:true,timeout:25000,maxBuffer:8000000});assert.equal(expected,0);return JSON.parse(r.stdout);}catch(e){if(expected&&e.code===expected)return JSON.parse(e.stdout||e.stderr);throw e;}}
let target,started=false;
async function plan(name,actions,expected=0,extra=[]){const file=path.join(work,name+'.json');await writeJSON(file,{actions});return command('run',['--tab',target,'--plan',file,...extra],expected);}
try {
  const launch=await command('launch',['--headless']);started=true;target=(await command('new',['--url',`http://127.0.0.1:${server.address().port}/`])).targetId;
  await plan('clear',[{type:'waitFor',expression:"!!document.querySelector('#text')"},{type:'fill',selector:'#text',text:''},{type:'assert',expression:"document.querySelector('#text').value===''"}]);pass('Empty text fill still clears an input; rejected baseline hypothesis is covered');
  let r=await plan('checkbox',[{type:'fill',selector:'#check',text:'hello'}],1);assert.match(r.steps[0].error,/supported text input/);r=await plan('checkbox-unchanged',[{type:'assert',expression:"!document.querySelector('#check').checked"}]);assert(r.ok);pass('Unsupported fill fails before changing a checkbox');
  r=await plan('hidden',[{type:'click',selector:'#hidden'}],1);assert.match(r.steps[0].error,/not visible/);await plan('hidden-unchanged',[{type:'assert',expression:'window.hiddenClicked!==true'}]);pass('An opacity-zero ancestor prevents pointer interaction');
  await plan('focus-setup',[{type:'eval',expression:"document.querySelector('#text').onmouseup=()=>document.querySelector('#other').focus();true"}]);r=await plan('focus',[{type:'fill',selector:'#text',text:'must not leak'}],1);assert.match(r.steps[0].error,/Focus moved/);await plan('focus-unchanged',[{type:'assert',expression:"document.querySelector('#other').value==='untouched'"}]);pass('Focus redirection cannot silently type into another field');
  r=await plan('invalid',[{type:'eval',expression:'window.unexpectedChange=true'},{type:'typo'}],1);assert.match(r.error,/Unknown action/);await plan('invalid-unchanged',[{type:'assert',expression:'window.unexpectedChange!==true'}]);pass('Invalid late actions are rejected before earlier page mutations');
  const collision=path.join(work,'collision.json');await writeJSON(collision,{actions:[{type:'traceStart'},{type:'traceStop',path:'collision.json'}]});r=await command('run',['--tab',target,'--plan',collision],1);assert.match(r.error,/distinct/);assert(Array.isArray(JSON.parse(await fs.readFile(collision,'utf8')).actions));pass('Trace output cannot overwrite its scenario input');
  r=await plan('failed-trace',[{type:'traceStart'},{type:'assert',expression:'false'},{type:'traceStop',path:'failed-trace-output.json'}],1);assert(!r.ok);assert(r.steps.some(s=>s.type==='traceStop'&&s.ok&&s.recoveredAfterFailure));assert(Array.isArray(JSON.parse(await fs.readFile(path.join(work,'failed-trace-output.json'),'utf8')).traceEvents));pass('A failed assertion retains the requested parseable trace');
  const start=Date.now();r=await plan('never-resolves',[{type:'waitFor',expression:'new Promise(()=>{})',timeoutMs:100}],1);assert(!r.ok);assert(Date.now()-start<3000);pass('waitFor respects its deadline for a never-resolving promise');
  const slow=path.join(work,'slow.json');await writeJSON(slow,{actions:[{type:'wait',ms:800}]});const first=command('run',['--tab',target,'--plan',slow]);
  for(let i=0;i<100;i++){if(await fs.access(path.join(state,'operation.lock')).then(()=>true,()=>false))break;await delay(10);}
  r=await plan('concurrent',[{type:'eval',expression:'window.concurrentMutation=true'}],1);assert.match(r.error,/locked/);await first;await plan('concurrent-unchanged',[{type:'assert',expression:'window.concurrentMutation!==true'}]);pass('Concurrent owned-browser mutation is rejected before execution');
  const session=JSON.parse(await fs.readFile(path.join(state,'session.json'),'utf8')),tab=(await fetchJSON(session.endpoint+'/json/list')).find(t=>t.id===target),external=await CDP.connect(tab.webSocketDebuggerUrl);
  try{await external.send('Emulation.setDeviceMetricsOverride',{width:640,height:700,deviceScaleFactor:1,mobile:false});await plan('read-only',[{type:'inspect'}]);const reply=await external.send('Runtime.evaluate',{expression:'innerWidth',returnByValue:true});assert.equal(reply.result.value,640);await external.send('Emulation.clearDeviceMetricsOverride');}finally{external.close();}pass('A scenario without emulation changes preserves another client\'s viewport');
  r=await plan('event-limit',[{type:'eval',expression:"console.log(...Array(100).fill('fixture'));true"},{type:'assertEvents',match:{kind:'exception'},maxCount:0}],1);assert(r.droppedEvents>0);assert.match(r.steps.at(-1).error,/incomplete/);pass('Truncated console evidence cannot pass an absence assertion');
  r=await plan('style-cost',[{type:'eval',expression:"document.body.innerHTML='<p>visible text</p>'.repeat(2000);true"},{type:'designAudit'}]);performanceEvidence.baselineStyleCalls=4500;performanceEvidence.currentStyleCalls=r.steps.find(s=>s.type==='designAudit').result.coverage.computedStyleReads;assert(performanceEvidence.currentStyleCalls<1500);pass('Design sampling stops early instead of measuring every candidate twice');
  const report=path.join(work,'compact-report.json'),file=path.join(work,'compact.json');await writeJSON(file,{actions:[{type:'inspect'}]});const compact=await exec(process.execPath,[gateway,'chrome','run','--state-dir',state,'--tab',target,'--plan',file,'--out',report,'--overwrite'],{windowsHide:true,maxBuffer:8000000});const brief=JSON.parse(compact.stdout),full=JSON.parse(await fs.readFile(report,'utf8'));assert(brief.ok);assert(full.steps[0].result.headings);assert.equal(brief.steps,undefined);performanceEvidence.fullReportBytes=Buffer.byteLength(JSON.stringify(full,null,2));performanceEvidence.compactStdoutBytes=Buffer.byteLength(compact.stdout);pass('One-entry compact mode saves the complete browser evidence');
  await writeJSON(path.join(work,'adversarial-browser-validation.json'),{testedAt:new Date().toISOString(),browser:launch.browser,checks,performanceEvidence,allPassed:true});
}finally{if(started)await command('stop');await new Promise(r=>server.close(r));}
