import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';
import {validatePlan,planPath} from '../web-debug/scripts/plan.mjs';
import {CDP,writeJSON,atomicOutput,appendPrivate,acquireLock} from '../web-debug/scripts/common.mjs';

test('H-1 rejects absolute paths, traversal, device names and alternate data streams',()=>{for(const file of ['../../outside.png','/tmp/outside.png','C:\\outside.png','\\\\host\\share\\outside.png','inputs/../outside.js','inputs/a.js:secret','inputs/CON','inputs/file.js.'])assert.throws(()=>planPath(file,'input'));});
test('H-1 inputs are curated separately from generated artifacts',()=>{assert.equal(planPath('inputs/repro.js','input'),'inputs/repro.js');assert.throws(()=>planPath('session.json','input'),/inputs/);assert.throws(()=>planPath('inputs/screenshot.png','screenshot'),/inputs/);assert.throws(()=>planPath('source.js','screenshot'),/png/);});
test('H-1 no-clobber preserves reports and a destination created after preflight',async()=>{const root=path.resolve('work/review-security-unit');await fs.mkdir(root,{recursive:true});const dir=await fs.mkdtemp(path.join(root,'case-')),file=path.join(dir,'report.json');await assert.rejects(atomicOutput(file,async temporary=>{await fs.writeFile(temporary,'new report');await fs.writeFile(file,'concurrent owner');},{overwrite:false}),/EEXIST/);assert.equal(await fs.readFile(file,'utf8'),'concurrent owner');await assert.rejects(writeJSON(file,{ok:true},{overwrite:false}));assert.equal(await fs.readFile(file,'utf8'),'concurrent owner');});
test('H-2 raw CDP requires caller policy outside the plan',()=>{assert.throws(()=>validatePlan({actions:[{type:'cdp',method:'Network.getCookies'}]}),/allow-raw-cdp/);validatePlan({actions:[{type:'cdp',method:'Network.getCookies'}]},{allowRawCdp:true});assert.throws(()=>validatePlan({allowRawCdp:true,actions:[{type:'inspect'}]}),/Unknown plan field/);});
test('H-2 raw navigation and browser-protection bypass do not evade guards',()=>{assert.throws(()=>validatePlan({actions:[{type:'cdp',method:'Page.navigate',params:{url:'file:///private'}}]},{allowRawCdp:true}),/http/);for(const method of ['Security.setIgnoreCertificateErrors','Security.setOverrideCertificateErrors','Page.setBypassCSP'])assert.throws(()=>validatePlan({actions:[{type:'cdp',method,params:{ignore:true}}]},{allowRawCdp:true}),/protections/);});
test('read-only mode permits observations but rejects custom script and mutations',()=>{validatePlan({actions:[{type:'waitForSelector',selector:'main'},{type:'inspect'},{type:'screenshot',path:'screen.png'}]},{readOnly:true});for(const action of [{type:'eval',expression:'1'},{type:'assert',expression:'true'},{type:'waitFor',expression:'true'},{type:'click',selector:'button'},{type:'cdp',method:'DOM.getDocument'}])assert.throws(()=>validatePlan({actions:[action]},{readOnly:true,allowRawCdp:true}),/read-only/);});
test('safe CDP methods remain usable without enabling unrestricted passthrough',()=>{validatePlan({actions:[{type:'cdp',method:'DOMSnapshot.captureSnapshot',params:{computedStyles:[]}}]});assert.throws(()=>validatePlan({actions:[{type:'cdp',method:'Network.setCacheDisabled',params:{cacheDisabled:'true'}}]}),/boolean/);});
test('custom page JavaScript is caller opt-in and cannot enable itself from a plan',()=>{assert.throws(()=>validatePlan({actions:[{type:'eval',expression:'1'}]}),/allow-script/);validatePlan({actions:[{type:'eval',expression:'1'}]},{allowScript:true});assert.throws(()=>validatePlan({allowScript:true,actions:[{type:'inspect'}]}),/Unknown plan field/);});
test('L-4 oversized protocol frames fail a configured bounded client',()=>{const socket=new EventTarget();let closed=false;socket.send=()=>{};socket.close=()=>{closed=true;};const cdp=new CDP(socket,{maxMessageBytes:64});socket.dispatchEvent(new MessageEvent('message',{data:'x'.repeat(65)}));assert(closed);assert.equal(cdp.protocolErrors,1);});
test('L-5 append refuses links and preserves their targets',async()=>{const root=path.resolve('work/review-security-unit');await fs.mkdir(root,{recursive:true});const dir=await fs.mkdtemp(path.join(root,'case-')),source=path.join(dir,'source'),link=path.join(dir,'link');await fs.writeFile(source,'original');await fs.symlink(source,link,'file');await assert.rejects(appendPrivate(link,'changed'));assert.equal(await fs.readFile(source,'utf8'),'original');});
test('L-5 stale lock errors include owner status without deleting a possibly shared lock',async()=>{const root=path.resolve('work/review-security-unit');await fs.mkdir(root,{recursive:true});const dir=await fs.mkdtemp(path.join(root,'case-')),file=path.join(dir,'operation.lock');await writeJSON(file,{pid:2147483647,startedAt:'2020-01-01T00:00:00Z'});await assert.rejects(acquireLock(file),/stale|status unavailable/);assert.equal(JSON.parse(await fs.readFile(file,'utf8')).pid,2147483647);});
test('L-2 POSIX evidence files default to owner-only permissions',{skip:process.platform==='win32'},async()=>{const root=path.resolve('work/review-security-unit');await fs.mkdir(root,{recursive:true});const dir=await fs.mkdtemp(path.join(root,'case-')),file=path.join(dir,'report.json');await writeJSON(file,{ok:true});assert.equal((await fs.stat(file)).mode&0o777,0o600);});
